version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-lambdacontrole
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lambdacontrole
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./config/sql/initial_schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - lambdacontroleitau

  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lambda-lambdacontrole
    ports:
      - "9000:8080"
    networks:
      - lambdacontroleitau
    depends_on:
      - mysql

networks:
  lambdacontroleitau:
    driver: bridge
