"""Initial schema creation

Revision ID: 317f492f38cd
Revises: 
Create Date: 2024-11-23 15:52:24.654147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '317f492f38cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_status')
    op.drop_index('name', table_name='tables')
    op.drop_table('tables')
    op.drop_table('table_partition_exec')
    op.drop_table('approval_status')
    op.drop_table('task_table')
    op.drop_table('partitions')
    op.drop_table('task_executor')
    op.drop_table('dependencies')
    # ### end Alembic commands ###


def upgrade() -> None:
    op.create_table('tables',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('requires_approval', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('last_modified_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table(
        'table_execution',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('table_id', mysql.INTEGER(), nullable=False),
        sa.Column('date_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('source', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
        sa.Column('deletion_date', mysql.DATETIME(), nullable=True), 
        sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='fk_table_execution_table', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependency_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['tables.id'], name='dependencies_ibfk_2'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='dependencies_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table(
        'task_executor',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('alias', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
        sa.Column('description', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
        sa.Column('method', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),  
        sa.Column('sqs_arn', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1024), nullable=True),  
        sa.Column('stf_arn', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1024), nullable=True),  
        sa.Column('api_uri', mysql.VARCHAR(collation='utf8mb4_general_ci', length=1024), nullable=True), 
        sa.Column('kafka_topic', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),  
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    
    op.execute(
        """
        INSERT INTO task_executor (alias, description, method)
        VALUES ('step_function_executor', 'Chama uma stepfunction', 'stepfunction_process')
        """
    )

    op.create_table('partitions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('is_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='partitions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task_table',
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_executor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('params', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='task_table_ibfk_1'),
    sa.ForeignKeyConstraint(['task_executor_id'], ['task_executor.id'], name='task_table_ibfk_2'),
    sa.PrimaryKeyConstraint('table_id', 'task_executor_id', 'alias'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('approval_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('requested_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('approver_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='approval_status_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table(
        'table_partition_exec',
        sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('partition_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('value', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
        sa.Column('execution_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('deletion_date', mysql.TIMESTAMP(), nullable=True),
        sa.Column('deleted_by_user', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
        sa.Column('execution_id', mysql.INTEGER(), autoincrement=False, nullable=False),  
        sa.ForeignKeyConstraint(['partition_id'], ['partitions.id'], name='fk_partition', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='fk_table', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['execution_id'], ['table_execution.id'], name='fk_execution', ondelete='CASCADE'),  
        sa.PrimaryKeyConstraint('table_id', 'partition_id', 'value', 'execution_id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'    )

    op.create_index('name', 'tables', ['name'], unique=True)
    op.create_table('process_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partition_set', mysql.JSON(), nullable=False),
    sa.Column('status', mysql.ENUM('IDLE', 'RUNNING', 'EXECUTED', 'FAILED'), nullable=False),
    sa.Column('last_updated', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('execution_start_time', mysql.DATETIME(), nullable=True),
    sa.Column('execution_end_time', mysql.DATETIME(), nullable=True),
    sa.Column('execution_logs', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='process_status_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
