STATIC_SCHEDULE_PENDENT = 'pending'
STATIC_SCHEDULE_IN_PROGRESS = 'in_progress'
STATIC_SCHEDULE_COMPLETED = 'completed'
STATIC_SCHEDULE_FAILED = 'failed'
STATIC_SCHEDULE_WAITING_APPROVAL = 'waiting_approval'

STATIC_APPROVE_STATUS_PENDING = 'pending'
STATIC_APPROVE_STATUS_APPROVED = 'approved'
STATIC_APPROVE_STATUS_REJECTED = 'rejected'