from setuptools import setup, find_packages
from itaufluxcontrol.versioncontrol import version_control

setup(
    name='itaufluxcontrol',
    version=version_control['version'],
    description='Controle de fluxo Itaú',
    author='Leonardo Rodrigues',
    author_email='leonardo.a.rodrigues@itau-unibanco.com.br',
    url='',  
    packages=find_packages(where=".", exclude=("tests*", "docs*")),
    include_package_data=True,
    install_requires=[
        "alembic==1.14.0",
        "annotated-types==0.7.0",
        "aws-lambda-powertools==3.3.0",
        "boto3==1.35.68",
        "botocore==1.35.68",
        "certifi==2024.12.14",
        "cffi==1.17.1",
        "charset-normalizer==3.4.0",
        "cryptography==43.0.3",
        "eralchemy==1.5.0",
        "exceptiongroup==1.2.2",
        "graphviz==0.20.3",
        "greenlet==3.1.1",
        "idna==3.10",
        "injector==0.22.0",
        "Jinja2==3.1.4",
        "jmespath==1.0.1",
        "Mako==1.3.6",
        "MarkupSafe==3.0.2",
        "mysql-connector-python==9.1.0",
        "packaging==24.2",
        "pycparser==2.22",
        "pydantic==2.9.2",
        "pydantic_core==2.23.4",
        "PyMySQL==1.1.1",
        "python-dateutil==2.9.0.post0",
        "requests==2.32.3",
        "s3transfer==0.10.4",
        "six==1.16.0",
        "SQLAlchemy==2.0.36",
        "tzlocal==5.2",
        "urllib3==2.2.3"
    ],
    extras_require={
        "dev": [
            "pytest==8.3.4",
            "pytest-cov==6.0.0",
            "pytest-mock==3.14.0",
            "coverage==7.6.9",
            "tomli==2.2.1",
            "iniconfig==2.0.0",
            "pluggy==1.5.0",
            "flake8",
            "black",
        ],
    },
    entry_points={},
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.10',
)